math:functionOverloading.o implementation.o
	g++ functionOverloading.cpp implementation.cpp -o math

functionOverloading.o:functionOverloading.cpp
	g++ -c functionOverloading.cpp

implementation.o:implementation.cpp
	g++ -c implementation.cpp

clean:
	rm *.o math